name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login
      run: docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag estado-trenes-api:latest
    - name: Push
      run: docker push estado-trenes-api:latest
